### ISSUE TITLE
still unavailable on MELPA

### ISSUE THREAD

**Issue by ghost** [clarete/eosd#2]

**Comment by clarete** [comment]
Hi @taohansen, thanks for opening the issue. I didn't really work on this project for a while. I was looking forward to make some progress before publishing it somewhere else. Are you already using it? Is it worth releasing an initial version? Let me know what you think and thanks for your interest in this lil fun project!

**Comment by ghost** [comment]
I would try it if it were on MELPA, even without filter functionality, caching etc. I think it would already be _good enough_ for a first release.
