### ISSUE TITLE
Not working with EXWM

### ISSUE THREAD

**Issue by paulbdavis** [clarete/eosd#3]
I have `exec dbus-launch --exit-with-session emacs` in my `.xinitrc` to start emacs with EXWM

I load up the script and run `(eosd-start)` but nothing comes in to the notifications buffer

**Comment by clarete** [comment]
Hi @paulbdavis!

I'm also an EXWM user and I use a command line identical to the one you posted so there are good chances that it might work for you too.

Do you by any chance have any other dbus service running that could be capturing the messages? Maybe the `notification-daemon`?

If that's not the case, you should be able to `M-x eosd` and see some stuff coming up. If you don't see anything showing up and have some time to help debugging, I can suggest using [D-feet](https://wiki.gnome.org/action/show/Apps/DFeet) to see if the service is properly registered.

Also please let me know if you see anything weird on the `*Messages*` buffer.

Thank you.

**Comment by paulbdavis** [comment]
@clarete Yes, I think dunst had managed to grab it before eosd had a chance. I'll try again and close this if that was the issue

**Comment by paulbdavis** [comment]
Yes, that was the case.

**Comment by clarete** [comment]
Nice! I'm glad it's working now! Let me know what you think and what can be improved when you get a chance! \o/
